/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AutoplayerRouteImport } from './routes/autoplayer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutoplayerTestlabRouteImport } from './routes/autoplayer_.testlab'
import { Route as AutoplayerSettingsRouteImport } from './routes/autoplayer_.settings'
import { Route as AutoplayerQueueRouteImport } from './routes/autoplayer_.queue'
import { Route as AutoplayerOneshotRouteImport } from './routes/autoplayer_.oneshot'
import { Route as AutoplayerMiniRouteImport } from './routes/autoplayer_.mini'
import { Route as AutoplayerLibraryRouteImport } from './routes/autoplayer_.library'
import { Route as AutoplayerTestlabIndexRouteImport } from './routes/autoplayer_.testlab.index'
import { Route as AutoplayerTestlabLlmRouteImport } from './routes/autoplayer_.testlab.llm'
import { Route as AutoplayerTestlabE2eRouteImport } from './routes/autoplayer_.testlab.e2e'
import { Route as AutoplayerTestlabCoverRouteImport } from './routes/autoplayer_.testlab.cover'
import { Route as AutoplayerTestlabConnectionsRouteImport } from './routes/autoplayer_.testlab.connections'
import { Route as AutoplayerTestlabAceRouteImport } from './routes/autoplayer_.testlab.ace'
import { Route as ApiAutoplayerTestConnectionRouteImport } from './routes/api.autoplayer.test-connection'
import { Route as ApiAutoplayerSubmitAceRouteImport } from './routes/api.autoplayer.submit-ace'
import { Route as ApiAutoplayerSaveSongRouteImport } from './routes/api.autoplayer.save-song'
import { Route as ApiAutoplayerRefinePromptRouteImport } from './routes/api.autoplayer.refine-prompt'
import { Route as ApiAutoplayerPollAceRouteImport } from './routes/api.autoplayer.poll-ace'
import { Route as ApiAutoplayerOpenrouterModelsRouteImport } from './routes/api.autoplayer.openrouter-models'
import { Route as ApiAutoplayerOllamaModelsRouteImport } from './routes/api.autoplayer.ollama-models'
import { Route as ApiAutoplayerGenerateSongRouteImport } from './routes/api.autoplayer.generate-song'
import { Route as ApiAutoplayerGenerateCoverRouteImport } from './routes/api.autoplayer.generate-cover'
import { Route as ApiAutoplayerGenerateAlbumTrackRouteImport } from './routes/api.autoplayer.generate-album-track'
import { Route as ApiAutoplayerExtractPersonaRouteImport } from './routes/api.autoplayer.extract-persona'
import { Route as ApiAutoplayerEnhanceSessionRouteImport } from './routes/api.autoplayer.enhance-session'
import { Route as ApiAutoplayerEnhanceRequestRouteImport } from './routes/api.autoplayer.enhance-request'
import { Route as ApiAutoplayerEnhancePromptRouteImport } from './routes/api.autoplayer.enhance-prompt'
import { Route as ApiAutoplayerAceModelsRouteImport } from './routes/api.autoplayer.ace-models'
import { Route as ApiAutoplayerAudioSongIdRouteImport } from './routes/api.autoplayer.audio.$songId'

const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoplayerRoute = AutoplayerRouteImport.update({
  id: '/autoplayer',
  path: '/autoplayer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoplayerTestlabRoute = AutoplayerTestlabRouteImport.update({
  id: '/autoplayer_/testlab',
  path: '/autoplayer/testlab',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoplayerSettingsRoute = AutoplayerSettingsRouteImport.update({
  id: '/autoplayer_/settings',
  path: '/autoplayer/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoplayerQueueRoute = AutoplayerQueueRouteImport.update({
  id: '/autoplayer_/queue',
  path: '/autoplayer/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoplayerOneshotRoute = AutoplayerOneshotRouteImport.update({
  id: '/autoplayer_/oneshot',
  path: '/autoplayer/oneshot',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoplayerMiniRoute = AutoplayerMiniRouteImport.update({
  id: '/autoplayer_/mini',
  path: '/autoplayer/mini',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoplayerLibraryRoute = AutoplayerLibraryRouteImport.update({
  id: '/autoplayer_/library',
  path: '/autoplayer/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoplayerTestlabIndexRoute = AutoplayerTestlabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AutoplayerTestlabRoute,
} as any)
const AutoplayerTestlabLlmRoute = AutoplayerTestlabLlmRouteImport.update({
  id: '/llm',
  path: '/llm',
  getParentRoute: () => AutoplayerTestlabRoute,
} as any)
const AutoplayerTestlabE2eRoute = AutoplayerTestlabE2eRouteImport.update({
  id: '/e2e',
  path: '/e2e',
  getParentRoute: () => AutoplayerTestlabRoute,
} as any)
const AutoplayerTestlabCoverRoute = AutoplayerTestlabCoverRouteImport.update({
  id: '/cover',
  path: '/cover',
  getParentRoute: () => AutoplayerTestlabRoute,
} as any)
const AutoplayerTestlabConnectionsRoute =
  AutoplayerTestlabConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AutoplayerTestlabRoute,
  } as any)
const AutoplayerTestlabAceRoute = AutoplayerTestlabAceRouteImport.update({
  id: '/ace',
  path: '/ace',
  getParentRoute: () => AutoplayerTestlabRoute,
} as any)
const ApiAutoplayerTestConnectionRoute =
  ApiAutoplayerTestConnectionRouteImport.update({
    id: '/api/autoplayer/test-connection',
    path: '/api/autoplayer/test-connection',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerSubmitAceRoute = ApiAutoplayerSubmitAceRouteImport.update({
  id: '/api/autoplayer/submit-ace',
  path: '/api/autoplayer/submit-ace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutoplayerSaveSongRoute = ApiAutoplayerSaveSongRouteImport.update({
  id: '/api/autoplayer/save-song',
  path: '/api/autoplayer/save-song',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutoplayerRefinePromptRoute =
  ApiAutoplayerRefinePromptRouteImport.update({
    id: '/api/autoplayer/refine-prompt',
    path: '/api/autoplayer/refine-prompt',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerPollAceRoute = ApiAutoplayerPollAceRouteImport.update({
  id: '/api/autoplayer/poll-ace',
  path: '/api/autoplayer/poll-ace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutoplayerOpenrouterModelsRoute =
  ApiAutoplayerOpenrouterModelsRouteImport.update({
    id: '/api/autoplayer/openrouter-models',
    path: '/api/autoplayer/openrouter-models',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerOllamaModelsRoute =
  ApiAutoplayerOllamaModelsRouteImport.update({
    id: '/api/autoplayer/ollama-models',
    path: '/api/autoplayer/ollama-models',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerGenerateSongRoute =
  ApiAutoplayerGenerateSongRouteImport.update({
    id: '/api/autoplayer/generate-song',
    path: '/api/autoplayer/generate-song',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerGenerateCoverRoute =
  ApiAutoplayerGenerateCoverRouteImport.update({
    id: '/api/autoplayer/generate-cover',
    path: '/api/autoplayer/generate-cover',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerGenerateAlbumTrackRoute =
  ApiAutoplayerGenerateAlbumTrackRouteImport.update({
    id: '/api/autoplayer/generate-album-track',
    path: '/api/autoplayer/generate-album-track',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerExtractPersonaRoute =
  ApiAutoplayerExtractPersonaRouteImport.update({
    id: '/api/autoplayer/extract-persona',
    path: '/api/autoplayer/extract-persona',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerEnhanceSessionRoute =
  ApiAutoplayerEnhanceSessionRouteImport.update({
    id: '/api/autoplayer/enhance-session',
    path: '/api/autoplayer/enhance-session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerEnhanceRequestRoute =
  ApiAutoplayerEnhanceRequestRouteImport.update({
    id: '/api/autoplayer/enhance-request',
    path: '/api/autoplayer/enhance-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerEnhancePromptRoute =
  ApiAutoplayerEnhancePromptRouteImport.update({
    id: '/api/autoplayer/enhance-prompt',
    path: '/api/autoplayer/enhance-prompt',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerAceModelsRoute = ApiAutoplayerAceModelsRouteImport.update({
  id: '/api/autoplayer/ace-models',
  path: '/api/autoplayer/ace-models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutoplayerAudioSongIdRoute =
  ApiAutoplayerAudioSongIdRouteImport.update({
    id: '/api/autoplayer/audio/$songId',
    path: '/api/autoplayer/audio/$songId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autoplayer': typeof AutoplayerRoute
  '/mcp': typeof McpRoute
  '/rooms': typeof RoomsRoute
  '/autoplayer/library': typeof AutoplayerLibraryRoute
  '/autoplayer/mini': typeof AutoplayerMiniRoute
  '/autoplayer/oneshot': typeof AutoplayerOneshotRoute
  '/autoplayer/queue': typeof AutoplayerQueueRoute
  '/autoplayer/settings': typeof AutoplayerSettingsRoute
  '/autoplayer/testlab': typeof AutoplayerTestlabRouteWithChildren
  '/api/autoplayer/ace-models': typeof ApiAutoplayerAceModelsRoute
  '/api/autoplayer/enhance-prompt': typeof ApiAutoplayerEnhancePromptRoute
  '/api/autoplayer/enhance-request': typeof ApiAutoplayerEnhanceRequestRoute
  '/api/autoplayer/enhance-session': typeof ApiAutoplayerEnhanceSessionRoute
  '/api/autoplayer/extract-persona': typeof ApiAutoplayerExtractPersonaRoute
  '/api/autoplayer/generate-album-track': typeof ApiAutoplayerGenerateAlbumTrackRoute
  '/api/autoplayer/generate-cover': typeof ApiAutoplayerGenerateCoverRoute
  '/api/autoplayer/generate-song': typeof ApiAutoplayerGenerateSongRoute
  '/api/autoplayer/ollama-models': typeof ApiAutoplayerOllamaModelsRoute
  '/api/autoplayer/openrouter-models': typeof ApiAutoplayerOpenrouterModelsRoute
  '/api/autoplayer/poll-ace': typeof ApiAutoplayerPollAceRoute
  '/api/autoplayer/refine-prompt': typeof ApiAutoplayerRefinePromptRoute
  '/api/autoplayer/save-song': typeof ApiAutoplayerSaveSongRoute
  '/api/autoplayer/submit-ace': typeof ApiAutoplayerSubmitAceRoute
  '/api/autoplayer/test-connection': typeof ApiAutoplayerTestConnectionRoute
  '/autoplayer/testlab/ace': typeof AutoplayerTestlabAceRoute
  '/autoplayer/testlab/connections': typeof AutoplayerTestlabConnectionsRoute
  '/autoplayer/testlab/cover': typeof AutoplayerTestlabCoverRoute
  '/autoplayer/testlab/e2e': typeof AutoplayerTestlabE2eRoute
  '/autoplayer/testlab/llm': typeof AutoplayerTestlabLlmRoute
  '/autoplayer/testlab/': typeof AutoplayerTestlabIndexRoute
  '/api/autoplayer/audio/$songId': typeof ApiAutoplayerAudioSongIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autoplayer': typeof AutoplayerRoute
  '/mcp': typeof McpRoute
  '/rooms': typeof RoomsRoute
  '/autoplayer/library': typeof AutoplayerLibraryRoute
  '/autoplayer/mini': typeof AutoplayerMiniRoute
  '/autoplayer/oneshot': typeof AutoplayerOneshotRoute
  '/autoplayer/queue': typeof AutoplayerQueueRoute
  '/autoplayer/settings': typeof AutoplayerSettingsRoute
  '/api/autoplayer/ace-models': typeof ApiAutoplayerAceModelsRoute
  '/api/autoplayer/enhance-prompt': typeof ApiAutoplayerEnhancePromptRoute
  '/api/autoplayer/enhance-request': typeof ApiAutoplayerEnhanceRequestRoute
  '/api/autoplayer/enhance-session': typeof ApiAutoplayerEnhanceSessionRoute
  '/api/autoplayer/extract-persona': typeof ApiAutoplayerExtractPersonaRoute
  '/api/autoplayer/generate-album-track': typeof ApiAutoplayerGenerateAlbumTrackRoute
  '/api/autoplayer/generate-cover': typeof ApiAutoplayerGenerateCoverRoute
  '/api/autoplayer/generate-song': typeof ApiAutoplayerGenerateSongRoute
  '/api/autoplayer/ollama-models': typeof ApiAutoplayerOllamaModelsRoute
  '/api/autoplayer/openrouter-models': typeof ApiAutoplayerOpenrouterModelsRoute
  '/api/autoplayer/poll-ace': typeof ApiAutoplayerPollAceRoute
  '/api/autoplayer/refine-prompt': typeof ApiAutoplayerRefinePromptRoute
  '/api/autoplayer/save-song': typeof ApiAutoplayerSaveSongRoute
  '/api/autoplayer/submit-ace': typeof ApiAutoplayerSubmitAceRoute
  '/api/autoplayer/test-connection': typeof ApiAutoplayerTestConnectionRoute
  '/autoplayer/testlab/ace': typeof AutoplayerTestlabAceRoute
  '/autoplayer/testlab/connections': typeof AutoplayerTestlabConnectionsRoute
  '/autoplayer/testlab/cover': typeof AutoplayerTestlabCoverRoute
  '/autoplayer/testlab/e2e': typeof AutoplayerTestlabE2eRoute
  '/autoplayer/testlab/llm': typeof AutoplayerTestlabLlmRoute
  '/autoplayer/testlab': typeof AutoplayerTestlabIndexRoute
  '/api/autoplayer/audio/$songId': typeof ApiAutoplayerAudioSongIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autoplayer': typeof AutoplayerRoute
  '/mcp': typeof McpRoute
  '/rooms': typeof RoomsRoute
  '/autoplayer_/library': typeof AutoplayerLibraryRoute
  '/autoplayer_/mini': typeof AutoplayerMiniRoute
  '/autoplayer_/oneshot': typeof AutoplayerOneshotRoute
  '/autoplayer_/queue': typeof AutoplayerQueueRoute
  '/autoplayer_/settings': typeof AutoplayerSettingsRoute
  '/autoplayer_/testlab': typeof AutoplayerTestlabRouteWithChildren
  '/api/autoplayer/ace-models': typeof ApiAutoplayerAceModelsRoute
  '/api/autoplayer/enhance-prompt': typeof ApiAutoplayerEnhancePromptRoute
  '/api/autoplayer/enhance-request': typeof ApiAutoplayerEnhanceRequestRoute
  '/api/autoplayer/enhance-session': typeof ApiAutoplayerEnhanceSessionRoute
  '/api/autoplayer/extract-persona': typeof ApiAutoplayerExtractPersonaRoute
  '/api/autoplayer/generate-album-track': typeof ApiAutoplayerGenerateAlbumTrackRoute
  '/api/autoplayer/generate-cover': typeof ApiAutoplayerGenerateCoverRoute
  '/api/autoplayer/generate-song': typeof ApiAutoplayerGenerateSongRoute
  '/api/autoplayer/ollama-models': typeof ApiAutoplayerOllamaModelsRoute
  '/api/autoplayer/openrouter-models': typeof ApiAutoplayerOpenrouterModelsRoute
  '/api/autoplayer/poll-ace': typeof ApiAutoplayerPollAceRoute
  '/api/autoplayer/refine-prompt': typeof ApiAutoplayerRefinePromptRoute
  '/api/autoplayer/save-song': typeof ApiAutoplayerSaveSongRoute
  '/api/autoplayer/submit-ace': typeof ApiAutoplayerSubmitAceRoute
  '/api/autoplayer/test-connection': typeof ApiAutoplayerTestConnectionRoute
  '/autoplayer_/testlab/ace': typeof AutoplayerTestlabAceRoute
  '/autoplayer_/testlab/connections': typeof AutoplayerTestlabConnectionsRoute
  '/autoplayer_/testlab/cover': typeof AutoplayerTestlabCoverRoute
  '/autoplayer_/testlab/e2e': typeof AutoplayerTestlabE2eRoute
  '/autoplayer_/testlab/llm': typeof AutoplayerTestlabLlmRoute
  '/autoplayer_/testlab/': typeof AutoplayerTestlabIndexRoute
  '/api/autoplayer/audio/$songId': typeof ApiAutoplayerAudioSongIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/autoplayer'
    | '/mcp'
    | '/rooms'
    | '/autoplayer/library'
    | '/autoplayer/mini'
    | '/autoplayer/oneshot'
    | '/autoplayer/queue'
    | '/autoplayer/settings'
    | '/autoplayer/testlab'
    | '/api/autoplayer/ace-models'
    | '/api/autoplayer/enhance-prompt'
    | '/api/autoplayer/enhance-request'
    | '/api/autoplayer/enhance-session'
    | '/api/autoplayer/extract-persona'
    | '/api/autoplayer/generate-album-track'
    | '/api/autoplayer/generate-cover'
    | '/api/autoplayer/generate-song'
    | '/api/autoplayer/ollama-models'
    | '/api/autoplayer/openrouter-models'
    | '/api/autoplayer/poll-ace'
    | '/api/autoplayer/refine-prompt'
    | '/api/autoplayer/save-song'
    | '/api/autoplayer/submit-ace'
    | '/api/autoplayer/test-connection'
    | '/autoplayer/testlab/ace'
    | '/autoplayer/testlab/connections'
    | '/autoplayer/testlab/cover'
    | '/autoplayer/testlab/e2e'
    | '/autoplayer/testlab/llm'
    | '/autoplayer/testlab/'
    | '/api/autoplayer/audio/$songId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/autoplayer'
    | '/mcp'
    | '/rooms'
    | '/autoplayer/library'
    | '/autoplayer/mini'
    | '/autoplayer/oneshot'
    | '/autoplayer/queue'
    | '/autoplayer/settings'
    | '/api/autoplayer/ace-models'
    | '/api/autoplayer/enhance-prompt'
    | '/api/autoplayer/enhance-request'
    | '/api/autoplayer/enhance-session'
    | '/api/autoplayer/extract-persona'
    | '/api/autoplayer/generate-album-track'
    | '/api/autoplayer/generate-cover'
    | '/api/autoplayer/generate-song'
    | '/api/autoplayer/ollama-models'
    | '/api/autoplayer/openrouter-models'
    | '/api/autoplayer/poll-ace'
    | '/api/autoplayer/refine-prompt'
    | '/api/autoplayer/save-song'
    | '/api/autoplayer/submit-ace'
    | '/api/autoplayer/test-connection'
    | '/autoplayer/testlab/ace'
    | '/autoplayer/testlab/connections'
    | '/autoplayer/testlab/cover'
    | '/autoplayer/testlab/e2e'
    | '/autoplayer/testlab/llm'
    | '/autoplayer/testlab'
    | '/api/autoplayer/audio/$songId'
  id:
    | '__root__'
    | '/'
    | '/autoplayer'
    | '/mcp'
    | '/rooms'
    | '/autoplayer_/library'
    | '/autoplayer_/mini'
    | '/autoplayer_/oneshot'
    | '/autoplayer_/queue'
    | '/autoplayer_/settings'
    | '/autoplayer_/testlab'
    | '/api/autoplayer/ace-models'
    | '/api/autoplayer/enhance-prompt'
    | '/api/autoplayer/enhance-request'
    | '/api/autoplayer/enhance-session'
    | '/api/autoplayer/extract-persona'
    | '/api/autoplayer/generate-album-track'
    | '/api/autoplayer/generate-cover'
    | '/api/autoplayer/generate-song'
    | '/api/autoplayer/ollama-models'
    | '/api/autoplayer/openrouter-models'
    | '/api/autoplayer/poll-ace'
    | '/api/autoplayer/refine-prompt'
    | '/api/autoplayer/save-song'
    | '/api/autoplayer/submit-ace'
    | '/api/autoplayer/test-connection'
    | '/autoplayer_/testlab/ace'
    | '/autoplayer_/testlab/connections'
    | '/autoplayer_/testlab/cover'
    | '/autoplayer_/testlab/e2e'
    | '/autoplayer_/testlab/llm'
    | '/autoplayer_/testlab/'
    | '/api/autoplayer/audio/$songId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutoplayerRoute: typeof AutoplayerRoute
  McpRoute: typeof McpRoute
  RoomsRoute: typeof RoomsRoute
  AutoplayerLibraryRoute: typeof AutoplayerLibraryRoute
  AutoplayerMiniRoute: typeof AutoplayerMiniRoute
  AutoplayerOneshotRoute: typeof AutoplayerOneshotRoute
  AutoplayerQueueRoute: typeof AutoplayerQueueRoute
  AutoplayerSettingsRoute: typeof AutoplayerSettingsRoute
  AutoplayerTestlabRoute: typeof AutoplayerTestlabRouteWithChildren
  ApiAutoplayerAceModelsRoute: typeof ApiAutoplayerAceModelsRoute
  ApiAutoplayerEnhancePromptRoute: typeof ApiAutoplayerEnhancePromptRoute
  ApiAutoplayerEnhanceRequestRoute: typeof ApiAutoplayerEnhanceRequestRoute
  ApiAutoplayerEnhanceSessionRoute: typeof ApiAutoplayerEnhanceSessionRoute
  ApiAutoplayerExtractPersonaRoute: typeof ApiAutoplayerExtractPersonaRoute
  ApiAutoplayerGenerateAlbumTrackRoute: typeof ApiAutoplayerGenerateAlbumTrackRoute
  ApiAutoplayerGenerateCoverRoute: typeof ApiAutoplayerGenerateCoverRoute
  ApiAutoplayerGenerateSongRoute: typeof ApiAutoplayerGenerateSongRoute
  ApiAutoplayerOllamaModelsRoute: typeof ApiAutoplayerOllamaModelsRoute
  ApiAutoplayerOpenrouterModelsRoute: typeof ApiAutoplayerOpenrouterModelsRoute
  ApiAutoplayerPollAceRoute: typeof ApiAutoplayerPollAceRoute
  ApiAutoplayerRefinePromptRoute: typeof ApiAutoplayerRefinePromptRoute
  ApiAutoplayerSaveSongRoute: typeof ApiAutoplayerSaveSongRoute
  ApiAutoplayerSubmitAceRoute: typeof ApiAutoplayerSubmitAceRoute
  ApiAutoplayerTestConnectionRoute: typeof ApiAutoplayerTestConnectionRoute
  ApiAutoplayerAudioSongIdRoute: typeof ApiAutoplayerAudioSongIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoplayer': {
      id: '/autoplayer'
      path: '/autoplayer'
      fullPath: '/autoplayer'
      preLoaderRoute: typeof AutoplayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoplayer_/testlab': {
      id: '/autoplayer_/testlab'
      path: '/autoplayer/testlab'
      fullPath: '/autoplayer/testlab'
      preLoaderRoute: typeof AutoplayerTestlabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoplayer_/settings': {
      id: '/autoplayer_/settings'
      path: '/autoplayer/settings'
      fullPath: '/autoplayer/settings'
      preLoaderRoute: typeof AutoplayerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoplayer_/queue': {
      id: '/autoplayer_/queue'
      path: '/autoplayer/queue'
      fullPath: '/autoplayer/queue'
      preLoaderRoute: typeof AutoplayerQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoplayer_/oneshot': {
      id: '/autoplayer_/oneshot'
      path: '/autoplayer/oneshot'
      fullPath: '/autoplayer/oneshot'
      preLoaderRoute: typeof AutoplayerOneshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoplayer_/mini': {
      id: '/autoplayer_/mini'
      path: '/autoplayer/mini'
      fullPath: '/autoplayer/mini'
      preLoaderRoute: typeof AutoplayerMiniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoplayer_/library': {
      id: '/autoplayer_/library'
      path: '/autoplayer/library'
      fullPath: '/autoplayer/library'
      preLoaderRoute: typeof AutoplayerLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoplayer_/testlab/': {
      id: '/autoplayer_/testlab/'
      path: '/'
      fullPath: '/autoplayer/testlab/'
      preLoaderRoute: typeof AutoplayerTestlabIndexRouteImport
      parentRoute: typeof AutoplayerTestlabRoute
    }
    '/autoplayer_/testlab/llm': {
      id: '/autoplayer_/testlab/llm'
      path: '/llm'
      fullPath: '/autoplayer/testlab/llm'
      preLoaderRoute: typeof AutoplayerTestlabLlmRouteImport
      parentRoute: typeof AutoplayerTestlabRoute
    }
    '/autoplayer_/testlab/e2e': {
      id: '/autoplayer_/testlab/e2e'
      path: '/e2e'
      fullPath: '/autoplayer/testlab/e2e'
      preLoaderRoute: typeof AutoplayerTestlabE2eRouteImport
      parentRoute: typeof AutoplayerTestlabRoute
    }
    '/autoplayer_/testlab/cover': {
      id: '/autoplayer_/testlab/cover'
      path: '/cover'
      fullPath: '/autoplayer/testlab/cover'
      preLoaderRoute: typeof AutoplayerTestlabCoverRouteImport
      parentRoute: typeof AutoplayerTestlabRoute
    }
    '/autoplayer_/testlab/connections': {
      id: '/autoplayer_/testlab/connections'
      path: '/connections'
      fullPath: '/autoplayer/testlab/connections'
      preLoaderRoute: typeof AutoplayerTestlabConnectionsRouteImport
      parentRoute: typeof AutoplayerTestlabRoute
    }
    '/autoplayer_/testlab/ace': {
      id: '/autoplayer_/testlab/ace'
      path: '/ace'
      fullPath: '/autoplayer/testlab/ace'
      preLoaderRoute: typeof AutoplayerTestlabAceRouteImport
      parentRoute: typeof AutoplayerTestlabRoute
    }
    '/api/autoplayer/test-connection': {
      id: '/api/autoplayer/test-connection'
      path: '/api/autoplayer/test-connection'
      fullPath: '/api/autoplayer/test-connection'
      preLoaderRoute: typeof ApiAutoplayerTestConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/submit-ace': {
      id: '/api/autoplayer/submit-ace'
      path: '/api/autoplayer/submit-ace'
      fullPath: '/api/autoplayer/submit-ace'
      preLoaderRoute: typeof ApiAutoplayerSubmitAceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/save-song': {
      id: '/api/autoplayer/save-song'
      path: '/api/autoplayer/save-song'
      fullPath: '/api/autoplayer/save-song'
      preLoaderRoute: typeof ApiAutoplayerSaveSongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/refine-prompt': {
      id: '/api/autoplayer/refine-prompt'
      path: '/api/autoplayer/refine-prompt'
      fullPath: '/api/autoplayer/refine-prompt'
      preLoaderRoute: typeof ApiAutoplayerRefinePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/poll-ace': {
      id: '/api/autoplayer/poll-ace'
      path: '/api/autoplayer/poll-ace'
      fullPath: '/api/autoplayer/poll-ace'
      preLoaderRoute: typeof ApiAutoplayerPollAceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/openrouter-models': {
      id: '/api/autoplayer/openrouter-models'
      path: '/api/autoplayer/openrouter-models'
      fullPath: '/api/autoplayer/openrouter-models'
      preLoaderRoute: typeof ApiAutoplayerOpenrouterModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/ollama-models': {
      id: '/api/autoplayer/ollama-models'
      path: '/api/autoplayer/ollama-models'
      fullPath: '/api/autoplayer/ollama-models'
      preLoaderRoute: typeof ApiAutoplayerOllamaModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/generate-song': {
      id: '/api/autoplayer/generate-song'
      path: '/api/autoplayer/generate-song'
      fullPath: '/api/autoplayer/generate-song'
      preLoaderRoute: typeof ApiAutoplayerGenerateSongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/generate-cover': {
      id: '/api/autoplayer/generate-cover'
      path: '/api/autoplayer/generate-cover'
      fullPath: '/api/autoplayer/generate-cover'
      preLoaderRoute: typeof ApiAutoplayerGenerateCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/generate-album-track': {
      id: '/api/autoplayer/generate-album-track'
      path: '/api/autoplayer/generate-album-track'
      fullPath: '/api/autoplayer/generate-album-track'
      preLoaderRoute: typeof ApiAutoplayerGenerateAlbumTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/extract-persona': {
      id: '/api/autoplayer/extract-persona'
      path: '/api/autoplayer/extract-persona'
      fullPath: '/api/autoplayer/extract-persona'
      preLoaderRoute: typeof ApiAutoplayerExtractPersonaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/enhance-session': {
      id: '/api/autoplayer/enhance-session'
      path: '/api/autoplayer/enhance-session'
      fullPath: '/api/autoplayer/enhance-session'
      preLoaderRoute: typeof ApiAutoplayerEnhanceSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/enhance-request': {
      id: '/api/autoplayer/enhance-request'
      path: '/api/autoplayer/enhance-request'
      fullPath: '/api/autoplayer/enhance-request'
      preLoaderRoute: typeof ApiAutoplayerEnhanceRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/enhance-prompt': {
      id: '/api/autoplayer/enhance-prompt'
      path: '/api/autoplayer/enhance-prompt'
      fullPath: '/api/autoplayer/enhance-prompt'
      preLoaderRoute: typeof ApiAutoplayerEnhancePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/ace-models': {
      id: '/api/autoplayer/ace-models'
      path: '/api/autoplayer/ace-models'
      fullPath: '/api/autoplayer/ace-models'
      preLoaderRoute: typeof ApiAutoplayerAceModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/audio/$songId': {
      id: '/api/autoplayer/audio/$songId'
      path: '/api/autoplayer/audio/$songId'
      fullPath: '/api/autoplayer/audio/$songId'
      preLoaderRoute: typeof ApiAutoplayerAudioSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AutoplayerTestlabRouteChildren {
  AutoplayerTestlabAceRoute: typeof AutoplayerTestlabAceRoute
  AutoplayerTestlabConnectionsRoute: typeof AutoplayerTestlabConnectionsRoute
  AutoplayerTestlabCoverRoute: typeof AutoplayerTestlabCoverRoute
  AutoplayerTestlabE2eRoute: typeof AutoplayerTestlabE2eRoute
  AutoplayerTestlabLlmRoute: typeof AutoplayerTestlabLlmRoute
  AutoplayerTestlabIndexRoute: typeof AutoplayerTestlabIndexRoute
}

const AutoplayerTestlabRouteChildren: AutoplayerTestlabRouteChildren = {
  AutoplayerTestlabAceRoute: AutoplayerTestlabAceRoute,
  AutoplayerTestlabConnectionsRoute: AutoplayerTestlabConnectionsRoute,
  AutoplayerTestlabCoverRoute: AutoplayerTestlabCoverRoute,
  AutoplayerTestlabE2eRoute: AutoplayerTestlabE2eRoute,
  AutoplayerTestlabLlmRoute: AutoplayerTestlabLlmRoute,
  AutoplayerTestlabIndexRoute: AutoplayerTestlabIndexRoute,
}

const AutoplayerTestlabRouteWithChildren =
  AutoplayerTestlabRoute._addFileChildren(AutoplayerTestlabRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutoplayerRoute: AutoplayerRoute,
  McpRoute: McpRoute,
  RoomsRoute: RoomsRoute,
  AutoplayerLibraryRoute: AutoplayerLibraryRoute,
  AutoplayerMiniRoute: AutoplayerMiniRoute,
  AutoplayerOneshotRoute: AutoplayerOneshotRoute,
  AutoplayerQueueRoute: AutoplayerQueueRoute,
  AutoplayerSettingsRoute: AutoplayerSettingsRoute,
  AutoplayerTestlabRoute: AutoplayerTestlabRouteWithChildren,
  ApiAutoplayerAceModelsRoute: ApiAutoplayerAceModelsRoute,
  ApiAutoplayerEnhancePromptRoute: ApiAutoplayerEnhancePromptRoute,
  ApiAutoplayerEnhanceRequestRoute: ApiAutoplayerEnhanceRequestRoute,
  ApiAutoplayerEnhanceSessionRoute: ApiAutoplayerEnhanceSessionRoute,
  ApiAutoplayerExtractPersonaRoute: ApiAutoplayerExtractPersonaRoute,
  ApiAutoplayerGenerateAlbumTrackRoute: ApiAutoplayerGenerateAlbumTrackRoute,
  ApiAutoplayerGenerateCoverRoute: ApiAutoplayerGenerateCoverRoute,
  ApiAutoplayerGenerateSongRoute: ApiAutoplayerGenerateSongRoute,
  ApiAutoplayerOllamaModelsRoute: ApiAutoplayerOllamaModelsRoute,
  ApiAutoplayerOpenrouterModelsRoute: ApiAutoplayerOpenrouterModelsRoute,
  ApiAutoplayerPollAceRoute: ApiAutoplayerPollAceRoute,
  ApiAutoplayerRefinePromptRoute: ApiAutoplayerRefinePromptRoute,
  ApiAutoplayerSaveSongRoute: ApiAutoplayerSaveSongRoute,
  ApiAutoplayerSubmitAceRoute: ApiAutoplayerSubmitAceRoute,
  ApiAutoplayerTestConnectionRoute: ApiAutoplayerTestConnectionRoute,
  ApiAutoplayerAudioSongIdRoute: ApiAutoplayerAudioSongIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
