/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AutoplayerRouteImport } from './routes/autoplayer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoMcpTodosRouteImport } from './routes/demo/mcp-todos'
import { Route as DemoConvexRouteImport } from './routes/demo/convex'
import { Route as DemoAiStructuredRouteImport } from './routes/demo/ai-structured'
import { Route as DemoAiImageRouteImport } from './routes/demo/ai-image'
import { Route as DemoAiChatRouteImport } from './routes/demo/ai-chat'
import { Route as AutoplayerTestRouteImport } from './routes/autoplayer_.test'
import { Route as AutoplayerSettingsRouteImport } from './routes/autoplayer_.settings'
import { Route as DemoGuitarsIndexRouteImport } from './routes/demo/guitars/index'
import { Route as AutoplayerTestIndexRouteImport } from './routes/autoplayer_.test.index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoGuitarsGuitarIdRouteImport } from './routes/demo/guitars/$guitarId'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoApiMcpTodosRouteImport } from './routes/demo/api.mcp-todos'
import { Route as AutoplayerTestLlmRouteImport } from './routes/autoplayer_.test.llm'
import { Route as AutoplayerTestE2eRouteImport } from './routes/autoplayer_.test.e2e'
import { Route as AutoplayerTestCoverRouteImport } from './routes/autoplayer_.test.cover'
import { Route as AutoplayerTestConnectionsRouteImport } from './routes/autoplayer_.test.connections'
import { Route as AutoplayerTestAceRouteImport } from './routes/autoplayer_.test.ace'
import { Route as ApiAutoplayerTestConnectionRouteImport } from './routes/api.autoplayer.test-connection'
import { Route as ApiAutoplayerSubmitAceRouteImport } from './routes/api.autoplayer.submit-ace'
import { Route as ApiAutoplayerSaveSongRouteImport } from './routes/api.autoplayer.save-song'
import { Route as ApiAutoplayerRefinePromptRouteImport } from './routes/api.autoplayer.refine-prompt'
import { Route as ApiAutoplayerPollAceRouteImport } from './routes/api.autoplayer.poll-ace'
import { Route as ApiAutoplayerOllamaModelsRouteImport } from './routes/api.autoplayer.ollama-models'
import { Route as ApiAutoplayerGenerateSongRouteImport } from './routes/api.autoplayer.generate-song'
import { Route as ApiAutoplayerGenerateCoverRouteImport } from './routes/api.autoplayer.generate-cover'
import { Route as ApiAutoplayerEnhanceSessionRouteImport } from './routes/api.autoplayer.enhance-session'
import { Route as ApiAutoplayerEnhanceRequestRouteImport } from './routes/api.autoplayer.enhance-request'
import { Route as ApiAutoplayerEnhancePromptRouteImport } from './routes/api.autoplayer.enhance-prompt'
import { Route as ApiAutoplayerAceModelsRouteImport } from './routes/api.autoplayer.ace-models'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as DemoApiAiTtsRouteImport } from './routes/demo/api.ai.tts'
import { Route as DemoApiAiTranscriptionRouteImport } from './routes/demo/api.ai.transcription'
import { Route as DemoApiAiStructuredRouteImport } from './routes/demo/api.ai.structured'
import { Route as DemoApiAiImageRouteImport } from './routes/demo/api.ai.image'
import { Route as DemoApiAiChatRouteImport } from './routes/demo/api.ai.chat'
import { Route as ApiAutoplayerAudioSongIdRouteImport } from './routes/api.autoplayer.audio.$songId'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoplayerRoute = AutoplayerRouteImport.update({
  id: '/autoplayer',
  path: '/autoplayer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMcpTodosRoute = DemoMcpTodosRouteImport.update({
  id: '/demo/mcp-todos',
  path: '/demo/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexRoute = DemoConvexRouteImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiStructuredRoute = DemoAiStructuredRouteImport.update({
  id: '/demo/ai-structured',
  path: '/demo/ai-structured',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiImageRoute = DemoAiImageRouteImport.update({
  id: '/demo/ai-image',
  path: '/demo/ai-image',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiChatRoute = DemoAiChatRouteImport.update({
  id: '/demo/ai-chat',
  path: '/demo/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoplayerTestRoute = AutoplayerTestRouteImport.update({
  id: '/autoplayer_/test',
  path: '/autoplayer/test',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoplayerSettingsRoute = AutoplayerSettingsRouteImport.update({
  id: '/autoplayer_/settings',
  path: '/autoplayer/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGuitarsIndexRoute = DemoGuitarsIndexRouteImport.update({
  id: '/demo/guitars/',
  path: '/demo/guitars/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoplayerTestIndexRoute = AutoplayerTestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AutoplayerTestRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGuitarsGuitarIdRoute = DemoGuitarsGuitarIdRouteImport.update({
  id: '/demo/guitars/$guitarId',
  path: '/demo/guitars/$guitarId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiMcpTodosRoute = DemoApiMcpTodosRouteImport.update({
  id: '/demo/api/mcp-todos',
  path: '/demo/api/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoplayerTestLlmRoute = AutoplayerTestLlmRouteImport.update({
  id: '/llm',
  path: '/llm',
  getParentRoute: () => AutoplayerTestRoute,
} as any)
const AutoplayerTestE2eRoute = AutoplayerTestE2eRouteImport.update({
  id: '/e2e',
  path: '/e2e',
  getParentRoute: () => AutoplayerTestRoute,
} as any)
const AutoplayerTestCoverRoute = AutoplayerTestCoverRouteImport.update({
  id: '/cover',
  path: '/cover',
  getParentRoute: () => AutoplayerTestRoute,
} as any)
const AutoplayerTestConnectionsRoute =
  AutoplayerTestConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AutoplayerTestRoute,
  } as any)
const AutoplayerTestAceRoute = AutoplayerTestAceRouteImport.update({
  id: '/ace',
  path: '/ace',
  getParentRoute: () => AutoplayerTestRoute,
} as any)
const ApiAutoplayerTestConnectionRoute =
  ApiAutoplayerTestConnectionRouteImport.update({
    id: '/api/autoplayer/test-connection',
    path: '/api/autoplayer/test-connection',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerSubmitAceRoute = ApiAutoplayerSubmitAceRouteImport.update({
  id: '/api/autoplayer/submit-ace',
  path: '/api/autoplayer/submit-ace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutoplayerSaveSongRoute = ApiAutoplayerSaveSongRouteImport.update({
  id: '/api/autoplayer/save-song',
  path: '/api/autoplayer/save-song',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutoplayerRefinePromptRoute =
  ApiAutoplayerRefinePromptRouteImport.update({
    id: '/api/autoplayer/refine-prompt',
    path: '/api/autoplayer/refine-prompt',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerPollAceRoute = ApiAutoplayerPollAceRouteImport.update({
  id: '/api/autoplayer/poll-ace',
  path: '/api/autoplayer/poll-ace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutoplayerOllamaModelsRoute =
  ApiAutoplayerOllamaModelsRouteImport.update({
    id: '/api/autoplayer/ollama-models',
    path: '/api/autoplayer/ollama-models',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerGenerateSongRoute =
  ApiAutoplayerGenerateSongRouteImport.update({
    id: '/api/autoplayer/generate-song',
    path: '/api/autoplayer/generate-song',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerGenerateCoverRoute =
  ApiAutoplayerGenerateCoverRouteImport.update({
    id: '/api/autoplayer/generate-cover',
    path: '/api/autoplayer/generate-cover',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerEnhanceSessionRoute =
  ApiAutoplayerEnhanceSessionRouteImport.update({
    id: '/api/autoplayer/enhance-session',
    path: '/api/autoplayer/enhance-session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerEnhanceRequestRoute =
  ApiAutoplayerEnhanceRequestRouteImport.update({
    id: '/api/autoplayer/enhance-request',
    path: '/api/autoplayer/enhance-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerEnhancePromptRoute =
  ApiAutoplayerEnhancePromptRouteImport.update({
    id: '/api/autoplayer/enhance-prompt',
    path: '/api/autoplayer/enhance-prompt',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerAceModelsRoute = ApiAutoplayerAceModelsRouteImport.update({
  id: '/api/autoplayer/ace-models',
  path: '/api/autoplayer/ace-models',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiTtsRoute = DemoApiAiTtsRouteImport.update({
  id: '/demo/api/ai/tts',
  path: '/demo/api/ai/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiTranscriptionRoute = DemoApiAiTranscriptionRouteImport.update({
  id: '/demo/api/ai/transcription',
  path: '/demo/api/ai/transcription',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiStructuredRoute = DemoApiAiStructuredRouteImport.update({
  id: '/demo/api/ai/structured',
  path: '/demo/api/ai/structured',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiImageRoute = DemoApiAiImageRouteImport.update({
  id: '/demo/api/ai/image',
  path: '/demo/api/ai/image',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiChatRoute = DemoApiAiChatRouteImport.update({
  id: '/demo/api/ai/chat',
  path: '/demo/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutoplayerAudioSongIdRoute =
  ApiAutoplayerAudioSongIdRouteImport.update({
    id: '/api/autoplayer/audio/$songId',
    path: '/api/autoplayer/audio/$songId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autoplayer': typeof AutoplayerRoute
  '/mcp': typeof McpRoute
  '/autoplayer/settings': typeof AutoplayerSettingsRoute
  '/autoplayer/test': typeof AutoplayerTestRouteWithChildren
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/store': typeof DemoStoreRoute
  '/api/autoplayer/ace-models': typeof ApiAutoplayerAceModelsRoute
  '/api/autoplayer/enhance-prompt': typeof ApiAutoplayerEnhancePromptRoute
  '/api/autoplayer/enhance-request': typeof ApiAutoplayerEnhanceRequestRoute
  '/api/autoplayer/enhance-session': typeof ApiAutoplayerEnhanceSessionRoute
  '/api/autoplayer/generate-cover': typeof ApiAutoplayerGenerateCoverRoute
  '/api/autoplayer/generate-song': typeof ApiAutoplayerGenerateSongRoute
  '/api/autoplayer/ollama-models': typeof ApiAutoplayerOllamaModelsRoute
  '/api/autoplayer/poll-ace': typeof ApiAutoplayerPollAceRoute
  '/api/autoplayer/refine-prompt': typeof ApiAutoplayerRefinePromptRoute
  '/api/autoplayer/save-song': typeof ApiAutoplayerSaveSongRoute
  '/api/autoplayer/submit-ace': typeof ApiAutoplayerSubmitAceRoute
  '/api/autoplayer/test-connection': typeof ApiAutoplayerTestConnectionRoute
  '/autoplayer/test/ace': typeof AutoplayerTestAceRoute
  '/autoplayer/test/connections': typeof AutoplayerTestConnectionsRoute
  '/autoplayer/test/cover': typeof AutoplayerTestCoverRoute
  '/autoplayer/test/e2e': typeof AutoplayerTestE2eRoute
  '/autoplayer/test/llm': typeof AutoplayerTestLlmRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/autoplayer/test/': typeof AutoplayerTestIndexRoute
  '/demo/guitars/': typeof DemoGuitarsIndexRoute
  '/api/autoplayer/audio/$songId': typeof ApiAutoplayerAudioSongIdRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autoplayer': typeof AutoplayerRoute
  '/mcp': typeof McpRoute
  '/autoplayer/settings': typeof AutoplayerSettingsRoute
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/store': typeof DemoStoreRoute
  '/api/autoplayer/ace-models': typeof ApiAutoplayerAceModelsRoute
  '/api/autoplayer/enhance-prompt': typeof ApiAutoplayerEnhancePromptRoute
  '/api/autoplayer/enhance-request': typeof ApiAutoplayerEnhanceRequestRoute
  '/api/autoplayer/enhance-session': typeof ApiAutoplayerEnhanceSessionRoute
  '/api/autoplayer/generate-cover': typeof ApiAutoplayerGenerateCoverRoute
  '/api/autoplayer/generate-song': typeof ApiAutoplayerGenerateSongRoute
  '/api/autoplayer/ollama-models': typeof ApiAutoplayerOllamaModelsRoute
  '/api/autoplayer/poll-ace': typeof ApiAutoplayerPollAceRoute
  '/api/autoplayer/refine-prompt': typeof ApiAutoplayerRefinePromptRoute
  '/api/autoplayer/save-song': typeof ApiAutoplayerSaveSongRoute
  '/api/autoplayer/submit-ace': typeof ApiAutoplayerSubmitAceRoute
  '/api/autoplayer/test-connection': typeof ApiAutoplayerTestConnectionRoute
  '/autoplayer/test/ace': typeof AutoplayerTestAceRoute
  '/autoplayer/test/connections': typeof AutoplayerTestConnectionsRoute
  '/autoplayer/test/cover': typeof AutoplayerTestCoverRoute
  '/autoplayer/test/e2e': typeof AutoplayerTestE2eRoute
  '/autoplayer/test/llm': typeof AutoplayerTestLlmRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/autoplayer/test': typeof AutoplayerTestIndexRoute
  '/demo/guitars': typeof DemoGuitarsIndexRoute
  '/api/autoplayer/audio/$songId': typeof ApiAutoplayerAudioSongIdRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autoplayer': typeof AutoplayerRoute
  '/mcp': typeof McpRoute
  '/autoplayer_/settings': typeof AutoplayerSettingsRoute
  '/autoplayer_/test': typeof AutoplayerTestRouteWithChildren
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/store': typeof DemoStoreRoute
  '/api/autoplayer/ace-models': typeof ApiAutoplayerAceModelsRoute
  '/api/autoplayer/enhance-prompt': typeof ApiAutoplayerEnhancePromptRoute
  '/api/autoplayer/enhance-request': typeof ApiAutoplayerEnhanceRequestRoute
  '/api/autoplayer/enhance-session': typeof ApiAutoplayerEnhanceSessionRoute
  '/api/autoplayer/generate-cover': typeof ApiAutoplayerGenerateCoverRoute
  '/api/autoplayer/generate-song': typeof ApiAutoplayerGenerateSongRoute
  '/api/autoplayer/ollama-models': typeof ApiAutoplayerOllamaModelsRoute
  '/api/autoplayer/poll-ace': typeof ApiAutoplayerPollAceRoute
  '/api/autoplayer/refine-prompt': typeof ApiAutoplayerRefinePromptRoute
  '/api/autoplayer/save-song': typeof ApiAutoplayerSaveSongRoute
  '/api/autoplayer/submit-ace': typeof ApiAutoplayerSubmitAceRoute
  '/api/autoplayer/test-connection': typeof ApiAutoplayerTestConnectionRoute
  '/autoplayer_/test/ace': typeof AutoplayerTestAceRoute
  '/autoplayer_/test/connections': typeof AutoplayerTestConnectionsRoute
  '/autoplayer_/test/cover': typeof AutoplayerTestCoverRoute
  '/autoplayer_/test/e2e': typeof AutoplayerTestE2eRoute
  '/autoplayer_/test/llm': typeof AutoplayerTestLlmRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/autoplayer_/test/': typeof AutoplayerTestIndexRoute
  '/demo/guitars/': typeof DemoGuitarsIndexRoute
  '/api/autoplayer/audio/$songId': typeof ApiAutoplayerAudioSongIdRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/autoplayer'
    | '/mcp'
    | '/autoplayer/settings'
    | '/autoplayer/test'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/convex'
    | '/demo/mcp-todos'
    | '/demo/store'
    | '/api/autoplayer/ace-models'
    | '/api/autoplayer/enhance-prompt'
    | '/api/autoplayer/enhance-request'
    | '/api/autoplayer/enhance-session'
    | '/api/autoplayer/generate-cover'
    | '/api/autoplayer/generate-song'
    | '/api/autoplayer/ollama-models'
    | '/api/autoplayer/poll-ace'
    | '/api/autoplayer/refine-prompt'
    | '/api/autoplayer/save-song'
    | '/api/autoplayer/submit-ace'
    | '/api/autoplayer/test-connection'
    | '/autoplayer/test/ace'
    | '/autoplayer/test/connections'
    | '/autoplayer/test/cover'
    | '/autoplayer/test/e2e'
    | '/autoplayer/test/llm'
    | '/demo/api/mcp-todos'
    | '/demo/api/names'
    | '/demo/guitars/$guitarId'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/autoplayer/test/'
    | '/demo/guitars/'
    | '/api/autoplayer/audio/$songId'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/autoplayer'
    | '/mcp'
    | '/autoplayer/settings'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/convex'
    | '/demo/mcp-todos'
    | '/demo/store'
    | '/api/autoplayer/ace-models'
    | '/api/autoplayer/enhance-prompt'
    | '/api/autoplayer/enhance-request'
    | '/api/autoplayer/enhance-session'
    | '/api/autoplayer/generate-cover'
    | '/api/autoplayer/generate-song'
    | '/api/autoplayer/ollama-models'
    | '/api/autoplayer/poll-ace'
    | '/api/autoplayer/refine-prompt'
    | '/api/autoplayer/save-song'
    | '/api/autoplayer/submit-ace'
    | '/api/autoplayer/test-connection'
    | '/autoplayer/test/ace'
    | '/autoplayer/test/connections'
    | '/autoplayer/test/cover'
    | '/autoplayer/test/e2e'
    | '/autoplayer/test/llm'
    | '/demo/api/mcp-todos'
    | '/demo/api/names'
    | '/demo/guitars/$guitarId'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/autoplayer/test'
    | '/demo/guitars'
    | '/api/autoplayer/audio/$songId'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/autoplayer'
    | '/mcp'
    | '/autoplayer_/settings'
    | '/autoplayer_/test'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/convex'
    | '/demo/mcp-todos'
    | '/demo/store'
    | '/api/autoplayer/ace-models'
    | '/api/autoplayer/enhance-prompt'
    | '/api/autoplayer/enhance-request'
    | '/api/autoplayer/enhance-session'
    | '/api/autoplayer/generate-cover'
    | '/api/autoplayer/generate-song'
    | '/api/autoplayer/ollama-models'
    | '/api/autoplayer/poll-ace'
    | '/api/autoplayer/refine-prompt'
    | '/api/autoplayer/save-song'
    | '/api/autoplayer/submit-ace'
    | '/api/autoplayer/test-connection'
    | '/autoplayer_/test/ace'
    | '/autoplayer_/test/connections'
    | '/autoplayer_/test/cover'
    | '/autoplayer_/test/e2e'
    | '/autoplayer_/test/llm'
    | '/demo/api/mcp-todos'
    | '/demo/api/names'
    | '/demo/guitars/$guitarId'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/autoplayer_/test/'
    | '/demo/guitars/'
    | '/api/autoplayer/audio/$songId'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutoplayerRoute: typeof AutoplayerRoute
  McpRoute: typeof McpRoute
  AutoplayerSettingsRoute: typeof AutoplayerSettingsRoute
  AutoplayerTestRoute: typeof AutoplayerTestRouteWithChildren
  DemoAiChatRoute: typeof DemoAiChatRoute
  DemoAiImageRoute: typeof DemoAiImageRoute
  DemoAiStructuredRoute: typeof DemoAiStructuredRoute
  DemoConvexRoute: typeof DemoConvexRoute
  DemoMcpTodosRoute: typeof DemoMcpTodosRoute
  DemoStoreRoute: typeof DemoStoreRoute
  ApiAutoplayerAceModelsRoute: typeof ApiAutoplayerAceModelsRoute
  ApiAutoplayerEnhancePromptRoute: typeof ApiAutoplayerEnhancePromptRoute
  ApiAutoplayerEnhanceRequestRoute: typeof ApiAutoplayerEnhanceRequestRoute
  ApiAutoplayerEnhanceSessionRoute: typeof ApiAutoplayerEnhanceSessionRoute
  ApiAutoplayerGenerateCoverRoute: typeof ApiAutoplayerGenerateCoverRoute
  ApiAutoplayerGenerateSongRoute: typeof ApiAutoplayerGenerateSongRoute
  ApiAutoplayerOllamaModelsRoute: typeof ApiAutoplayerOllamaModelsRoute
  ApiAutoplayerPollAceRoute: typeof ApiAutoplayerPollAceRoute
  ApiAutoplayerRefinePromptRoute: typeof ApiAutoplayerRefinePromptRoute
  ApiAutoplayerSaveSongRoute: typeof ApiAutoplayerSaveSongRoute
  ApiAutoplayerSubmitAceRoute: typeof ApiAutoplayerSubmitAceRoute
  ApiAutoplayerTestConnectionRoute: typeof ApiAutoplayerTestConnectionRoute
  DemoApiMcpTodosRoute: typeof DemoApiMcpTodosRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoGuitarsGuitarIdRoute: typeof DemoGuitarsGuitarIdRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoGuitarsIndexRoute: typeof DemoGuitarsIndexRoute
  ApiAutoplayerAudioSongIdRoute: typeof ApiAutoplayerAudioSongIdRoute
  DemoApiAiChatRoute: typeof DemoApiAiChatRoute
  DemoApiAiImageRoute: typeof DemoApiAiImageRoute
  DemoApiAiStructuredRoute: typeof DemoApiAiStructuredRoute
  DemoApiAiTranscriptionRoute: typeof DemoApiAiTranscriptionRoute
  DemoApiAiTtsRoute: typeof DemoApiAiTtsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoplayer': {
      id: '/autoplayer'
      path: '/autoplayer'
      fullPath: '/autoplayer'
      preLoaderRoute: typeof AutoplayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/mcp-todos': {
      id: '/demo/mcp-todos'
      path: '/demo/mcp-todos'
      fullPath: '/demo/mcp-todos'
      preLoaderRoute: typeof DemoMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex': {
      id: '/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof DemoConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai-structured': {
      id: '/demo/ai-structured'
      path: '/demo/ai-structured'
      fullPath: '/demo/ai-structured'
      preLoaderRoute: typeof DemoAiStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai-image': {
      id: '/demo/ai-image'
      path: '/demo/ai-image'
      fullPath: '/demo/ai-image'
      preLoaderRoute: typeof DemoAiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai-chat': {
      id: '/demo/ai-chat'
      path: '/demo/ai-chat'
      fullPath: '/demo/ai-chat'
      preLoaderRoute: typeof DemoAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoplayer_/test': {
      id: '/autoplayer_/test'
      path: '/autoplayer/test'
      fullPath: '/autoplayer/test'
      preLoaderRoute: typeof AutoplayerTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoplayer_/settings': {
      id: '/autoplayer_/settings'
      path: '/autoplayer/settings'
      fullPath: '/autoplayer/settings'
      preLoaderRoute: typeof AutoplayerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/guitars/': {
      id: '/demo/guitars/'
      path: '/demo/guitars'
      fullPath: '/demo/guitars/'
      preLoaderRoute: typeof DemoGuitarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoplayer_/test/': {
      id: '/autoplayer_/test/'
      path: '/'
      fullPath: '/autoplayer/test/'
      preLoaderRoute: typeof AutoplayerTestIndexRouteImport
      parentRoute: typeof AutoplayerTestRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/guitars/$guitarId': {
      id: '/demo/guitars/$guitarId'
      path: '/demo/guitars/$guitarId'
      fullPath: '/demo/guitars/$guitarId'
      preLoaderRoute: typeof DemoGuitarsGuitarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/mcp-todos': {
      id: '/demo/api/mcp-todos'
      path: '/demo/api/mcp-todos'
      fullPath: '/demo/api/mcp-todos'
      preLoaderRoute: typeof DemoApiMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoplayer_/test/llm': {
      id: '/autoplayer_/test/llm'
      path: '/llm'
      fullPath: '/autoplayer/test/llm'
      preLoaderRoute: typeof AutoplayerTestLlmRouteImport
      parentRoute: typeof AutoplayerTestRoute
    }
    '/autoplayer_/test/e2e': {
      id: '/autoplayer_/test/e2e'
      path: '/e2e'
      fullPath: '/autoplayer/test/e2e'
      preLoaderRoute: typeof AutoplayerTestE2eRouteImport
      parentRoute: typeof AutoplayerTestRoute
    }
    '/autoplayer_/test/cover': {
      id: '/autoplayer_/test/cover'
      path: '/cover'
      fullPath: '/autoplayer/test/cover'
      preLoaderRoute: typeof AutoplayerTestCoverRouteImport
      parentRoute: typeof AutoplayerTestRoute
    }
    '/autoplayer_/test/connections': {
      id: '/autoplayer_/test/connections'
      path: '/connections'
      fullPath: '/autoplayer/test/connections'
      preLoaderRoute: typeof AutoplayerTestConnectionsRouteImport
      parentRoute: typeof AutoplayerTestRoute
    }
    '/autoplayer_/test/ace': {
      id: '/autoplayer_/test/ace'
      path: '/ace'
      fullPath: '/autoplayer/test/ace'
      preLoaderRoute: typeof AutoplayerTestAceRouteImport
      parentRoute: typeof AutoplayerTestRoute
    }
    '/api/autoplayer/test-connection': {
      id: '/api/autoplayer/test-connection'
      path: '/api/autoplayer/test-connection'
      fullPath: '/api/autoplayer/test-connection'
      preLoaderRoute: typeof ApiAutoplayerTestConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/submit-ace': {
      id: '/api/autoplayer/submit-ace'
      path: '/api/autoplayer/submit-ace'
      fullPath: '/api/autoplayer/submit-ace'
      preLoaderRoute: typeof ApiAutoplayerSubmitAceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/save-song': {
      id: '/api/autoplayer/save-song'
      path: '/api/autoplayer/save-song'
      fullPath: '/api/autoplayer/save-song'
      preLoaderRoute: typeof ApiAutoplayerSaveSongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/refine-prompt': {
      id: '/api/autoplayer/refine-prompt'
      path: '/api/autoplayer/refine-prompt'
      fullPath: '/api/autoplayer/refine-prompt'
      preLoaderRoute: typeof ApiAutoplayerRefinePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/poll-ace': {
      id: '/api/autoplayer/poll-ace'
      path: '/api/autoplayer/poll-ace'
      fullPath: '/api/autoplayer/poll-ace'
      preLoaderRoute: typeof ApiAutoplayerPollAceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/ollama-models': {
      id: '/api/autoplayer/ollama-models'
      path: '/api/autoplayer/ollama-models'
      fullPath: '/api/autoplayer/ollama-models'
      preLoaderRoute: typeof ApiAutoplayerOllamaModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/generate-song': {
      id: '/api/autoplayer/generate-song'
      path: '/api/autoplayer/generate-song'
      fullPath: '/api/autoplayer/generate-song'
      preLoaderRoute: typeof ApiAutoplayerGenerateSongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/generate-cover': {
      id: '/api/autoplayer/generate-cover'
      path: '/api/autoplayer/generate-cover'
      fullPath: '/api/autoplayer/generate-cover'
      preLoaderRoute: typeof ApiAutoplayerGenerateCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/enhance-session': {
      id: '/api/autoplayer/enhance-session'
      path: '/api/autoplayer/enhance-session'
      fullPath: '/api/autoplayer/enhance-session'
      preLoaderRoute: typeof ApiAutoplayerEnhanceSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/enhance-request': {
      id: '/api/autoplayer/enhance-request'
      path: '/api/autoplayer/enhance-request'
      fullPath: '/api/autoplayer/enhance-request'
      preLoaderRoute: typeof ApiAutoplayerEnhanceRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/enhance-prompt': {
      id: '/api/autoplayer/enhance-prompt'
      path: '/api/autoplayer/enhance-prompt'
      fullPath: '/api/autoplayer/enhance-prompt'
      preLoaderRoute: typeof ApiAutoplayerEnhancePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/ace-models': {
      id: '/api/autoplayer/ace-models'
      path: '/api/autoplayer/ace-models'
      fullPath: '/api/autoplayer/ace-models'
      preLoaderRoute: typeof ApiAutoplayerAceModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/tts': {
      id: '/demo/api/ai/tts'
      path: '/demo/api/ai/tts'
      fullPath: '/demo/api/ai/tts'
      preLoaderRoute: typeof DemoApiAiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/transcription': {
      id: '/demo/api/ai/transcription'
      path: '/demo/api/ai/transcription'
      fullPath: '/demo/api/ai/transcription'
      preLoaderRoute: typeof DemoApiAiTranscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/structured': {
      id: '/demo/api/ai/structured'
      path: '/demo/api/ai/structured'
      fullPath: '/demo/api/ai/structured'
      preLoaderRoute: typeof DemoApiAiStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/image': {
      id: '/demo/api/ai/image'
      path: '/demo/api/ai/image'
      fullPath: '/demo/api/ai/image'
      preLoaderRoute: typeof DemoApiAiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/chat': {
      id: '/demo/api/ai/chat'
      path: '/demo/api/ai/chat'
      fullPath: '/demo/api/ai/chat'
      preLoaderRoute: typeof DemoApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/audio/$songId': {
      id: '/api/autoplayer/audio/$songId'
      path: '/api/autoplayer/audio/$songId'
      fullPath: '/api/autoplayer/audio/$songId'
      preLoaderRoute: typeof ApiAutoplayerAudioSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AutoplayerTestRouteChildren {
  AutoplayerTestAceRoute: typeof AutoplayerTestAceRoute
  AutoplayerTestConnectionsRoute: typeof AutoplayerTestConnectionsRoute
  AutoplayerTestCoverRoute: typeof AutoplayerTestCoverRoute
  AutoplayerTestE2eRoute: typeof AutoplayerTestE2eRoute
  AutoplayerTestLlmRoute: typeof AutoplayerTestLlmRoute
  AutoplayerTestIndexRoute: typeof AutoplayerTestIndexRoute
}

const AutoplayerTestRouteChildren: AutoplayerTestRouteChildren = {
  AutoplayerTestAceRoute: AutoplayerTestAceRoute,
  AutoplayerTestConnectionsRoute: AutoplayerTestConnectionsRoute,
  AutoplayerTestCoverRoute: AutoplayerTestCoverRoute,
  AutoplayerTestE2eRoute: AutoplayerTestE2eRoute,
  AutoplayerTestLlmRoute: AutoplayerTestLlmRoute,
  AutoplayerTestIndexRoute: AutoplayerTestIndexRoute,
}

const AutoplayerTestRouteWithChildren = AutoplayerTestRoute._addFileChildren(
  AutoplayerTestRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutoplayerRoute: AutoplayerRoute,
  McpRoute: McpRoute,
  AutoplayerSettingsRoute: AutoplayerSettingsRoute,
  AutoplayerTestRoute: AutoplayerTestRouteWithChildren,
  DemoAiChatRoute: DemoAiChatRoute,
  DemoAiImageRoute: DemoAiImageRoute,
  DemoAiStructuredRoute: DemoAiStructuredRoute,
  DemoConvexRoute: DemoConvexRoute,
  DemoMcpTodosRoute: DemoMcpTodosRoute,
  DemoStoreRoute: DemoStoreRoute,
  ApiAutoplayerAceModelsRoute: ApiAutoplayerAceModelsRoute,
  ApiAutoplayerEnhancePromptRoute: ApiAutoplayerEnhancePromptRoute,
  ApiAutoplayerEnhanceRequestRoute: ApiAutoplayerEnhanceRequestRoute,
  ApiAutoplayerEnhanceSessionRoute: ApiAutoplayerEnhanceSessionRoute,
  ApiAutoplayerGenerateCoverRoute: ApiAutoplayerGenerateCoverRoute,
  ApiAutoplayerGenerateSongRoute: ApiAutoplayerGenerateSongRoute,
  ApiAutoplayerOllamaModelsRoute: ApiAutoplayerOllamaModelsRoute,
  ApiAutoplayerPollAceRoute: ApiAutoplayerPollAceRoute,
  ApiAutoplayerRefinePromptRoute: ApiAutoplayerRefinePromptRoute,
  ApiAutoplayerSaveSongRoute: ApiAutoplayerSaveSongRoute,
  ApiAutoplayerSubmitAceRoute: ApiAutoplayerSubmitAceRoute,
  ApiAutoplayerTestConnectionRoute: ApiAutoplayerTestConnectionRoute,
  DemoApiMcpTodosRoute: DemoApiMcpTodosRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoGuitarsGuitarIdRoute: DemoGuitarsGuitarIdRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoGuitarsIndexRoute: DemoGuitarsIndexRoute,
  ApiAutoplayerAudioSongIdRoute: ApiAutoplayerAudioSongIdRoute,
  DemoApiAiChatRoute: DemoApiAiChatRoute,
  DemoApiAiImageRoute: DemoApiAiImageRoute,
  DemoApiAiStructuredRoute: DemoApiAiStructuredRoute,
  DemoApiAiTranscriptionRoute: DemoApiAiTranscriptionRoute,
  DemoApiAiTtsRoute: DemoApiAiTtsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
