/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AutoplayerRouteImport } from './routes/autoplayer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutoplayerTestRouteImport } from './routes/autoplayer_.test'
import { Route as AutoplayerSettingsRouteImport } from './routes/autoplayer_.settings'
import { Route as AutoplayerOneshotRouteImport } from './routes/autoplayer_.oneshot'
import { Route as AutoplayerLibraryRouteImport } from './routes/autoplayer_.library'
import { Route as AutoplayerTestIndexRouteImport } from './routes/autoplayer_.test.index'
import { Route as AutoplayerTestLlmRouteImport } from './routes/autoplayer_.test.llm'
import { Route as AutoplayerTestE2eRouteImport } from './routes/autoplayer_.test.e2e'
import { Route as AutoplayerTestCoverRouteImport } from './routes/autoplayer_.test.cover'
import { Route as AutoplayerTestConnectionsRouteImport } from './routes/autoplayer_.test.connections'
import { Route as AutoplayerTestAceRouteImport } from './routes/autoplayer_.test.ace'
import { Route as ApiAutoplayerTestConnectionRouteImport } from './routes/api.autoplayer.test-connection'
import { Route as ApiAutoplayerSubmitAceRouteImport } from './routes/api.autoplayer.submit-ace'
import { Route as ApiAutoplayerSaveSongRouteImport } from './routes/api.autoplayer.save-song'
import { Route as ApiAutoplayerRefinePromptRouteImport } from './routes/api.autoplayer.refine-prompt'
import { Route as ApiAutoplayerPollAceRouteImport } from './routes/api.autoplayer.poll-ace'
import { Route as ApiAutoplayerOllamaModelsRouteImport } from './routes/api.autoplayer.ollama-models'
import { Route as ApiAutoplayerGenerateSongRouteImport } from './routes/api.autoplayer.generate-song'
import { Route as ApiAutoplayerGenerateCoverRouteImport } from './routes/api.autoplayer.generate-cover'
import { Route as ApiAutoplayerEnhanceSessionRouteImport } from './routes/api.autoplayer.enhance-session'
import { Route as ApiAutoplayerEnhanceRequestRouteImport } from './routes/api.autoplayer.enhance-request'
import { Route as ApiAutoplayerEnhancePromptRouteImport } from './routes/api.autoplayer.enhance-prompt'
import { Route as ApiAutoplayerAceModelsRouteImport } from './routes/api.autoplayer.ace-models'
import { Route as ApiAutoplayerAudioSongIdRouteImport } from './routes/api.autoplayer.audio.$songId'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoplayerRoute = AutoplayerRouteImport.update({
  id: '/autoplayer',
  path: '/autoplayer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoplayerTestRoute = AutoplayerTestRouteImport.update({
  id: '/autoplayer_/test',
  path: '/autoplayer/test',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoplayerSettingsRoute = AutoplayerSettingsRouteImport.update({
  id: '/autoplayer_/settings',
  path: '/autoplayer/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoplayerOneshotRoute = AutoplayerOneshotRouteImport.update({
  id: '/autoplayer_/oneshot',
  path: '/autoplayer/oneshot',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoplayerLibraryRoute = AutoplayerLibraryRouteImport.update({
  id: '/autoplayer_/library',
  path: '/autoplayer/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoplayerTestIndexRoute = AutoplayerTestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AutoplayerTestRoute,
} as any)
const AutoplayerTestLlmRoute = AutoplayerTestLlmRouteImport.update({
  id: '/llm',
  path: '/llm',
  getParentRoute: () => AutoplayerTestRoute,
} as any)
const AutoplayerTestE2eRoute = AutoplayerTestE2eRouteImport.update({
  id: '/e2e',
  path: '/e2e',
  getParentRoute: () => AutoplayerTestRoute,
} as any)
const AutoplayerTestCoverRoute = AutoplayerTestCoverRouteImport.update({
  id: '/cover',
  path: '/cover',
  getParentRoute: () => AutoplayerTestRoute,
} as any)
const AutoplayerTestConnectionsRoute =
  AutoplayerTestConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AutoplayerTestRoute,
  } as any)
const AutoplayerTestAceRoute = AutoplayerTestAceRouteImport.update({
  id: '/ace',
  path: '/ace',
  getParentRoute: () => AutoplayerTestRoute,
} as any)
const ApiAutoplayerTestConnectionRoute =
  ApiAutoplayerTestConnectionRouteImport.update({
    id: '/api/autoplayer/test-connection',
    path: '/api/autoplayer/test-connection',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerSubmitAceRoute = ApiAutoplayerSubmitAceRouteImport.update({
  id: '/api/autoplayer/submit-ace',
  path: '/api/autoplayer/submit-ace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutoplayerSaveSongRoute = ApiAutoplayerSaveSongRouteImport.update({
  id: '/api/autoplayer/save-song',
  path: '/api/autoplayer/save-song',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutoplayerRefinePromptRoute =
  ApiAutoplayerRefinePromptRouteImport.update({
    id: '/api/autoplayer/refine-prompt',
    path: '/api/autoplayer/refine-prompt',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerPollAceRoute = ApiAutoplayerPollAceRouteImport.update({
  id: '/api/autoplayer/poll-ace',
  path: '/api/autoplayer/poll-ace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutoplayerOllamaModelsRoute =
  ApiAutoplayerOllamaModelsRouteImport.update({
    id: '/api/autoplayer/ollama-models',
    path: '/api/autoplayer/ollama-models',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerGenerateSongRoute =
  ApiAutoplayerGenerateSongRouteImport.update({
    id: '/api/autoplayer/generate-song',
    path: '/api/autoplayer/generate-song',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerGenerateCoverRoute =
  ApiAutoplayerGenerateCoverRouteImport.update({
    id: '/api/autoplayer/generate-cover',
    path: '/api/autoplayer/generate-cover',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerEnhanceSessionRoute =
  ApiAutoplayerEnhanceSessionRouteImport.update({
    id: '/api/autoplayer/enhance-session',
    path: '/api/autoplayer/enhance-session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerEnhanceRequestRoute =
  ApiAutoplayerEnhanceRequestRouteImport.update({
    id: '/api/autoplayer/enhance-request',
    path: '/api/autoplayer/enhance-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerEnhancePromptRoute =
  ApiAutoplayerEnhancePromptRouteImport.update({
    id: '/api/autoplayer/enhance-prompt',
    path: '/api/autoplayer/enhance-prompt',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutoplayerAceModelsRoute = ApiAutoplayerAceModelsRouteImport.update({
  id: '/api/autoplayer/ace-models',
  path: '/api/autoplayer/ace-models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutoplayerAudioSongIdRoute =
  ApiAutoplayerAudioSongIdRouteImport.update({
    id: '/api/autoplayer/audio/$songId',
    path: '/api/autoplayer/audio/$songId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autoplayer': typeof AutoplayerRoute
  '/mcp': typeof McpRoute
  '/autoplayer/library': typeof AutoplayerLibraryRoute
  '/autoplayer/oneshot': typeof AutoplayerOneshotRoute
  '/autoplayer/settings': typeof AutoplayerSettingsRoute
  '/autoplayer/test': typeof AutoplayerTestRouteWithChildren
  '/api/autoplayer/ace-models': typeof ApiAutoplayerAceModelsRoute
  '/api/autoplayer/enhance-prompt': typeof ApiAutoplayerEnhancePromptRoute
  '/api/autoplayer/enhance-request': typeof ApiAutoplayerEnhanceRequestRoute
  '/api/autoplayer/enhance-session': typeof ApiAutoplayerEnhanceSessionRoute
  '/api/autoplayer/generate-cover': typeof ApiAutoplayerGenerateCoverRoute
  '/api/autoplayer/generate-song': typeof ApiAutoplayerGenerateSongRoute
  '/api/autoplayer/ollama-models': typeof ApiAutoplayerOllamaModelsRoute
  '/api/autoplayer/poll-ace': typeof ApiAutoplayerPollAceRoute
  '/api/autoplayer/refine-prompt': typeof ApiAutoplayerRefinePromptRoute
  '/api/autoplayer/save-song': typeof ApiAutoplayerSaveSongRoute
  '/api/autoplayer/submit-ace': typeof ApiAutoplayerSubmitAceRoute
  '/api/autoplayer/test-connection': typeof ApiAutoplayerTestConnectionRoute
  '/autoplayer/test/ace': typeof AutoplayerTestAceRoute
  '/autoplayer/test/connections': typeof AutoplayerTestConnectionsRoute
  '/autoplayer/test/cover': typeof AutoplayerTestCoverRoute
  '/autoplayer/test/e2e': typeof AutoplayerTestE2eRoute
  '/autoplayer/test/llm': typeof AutoplayerTestLlmRoute
  '/autoplayer/test/': typeof AutoplayerTestIndexRoute
  '/api/autoplayer/audio/$songId': typeof ApiAutoplayerAudioSongIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autoplayer': typeof AutoplayerRoute
  '/mcp': typeof McpRoute
  '/autoplayer/library': typeof AutoplayerLibraryRoute
  '/autoplayer/oneshot': typeof AutoplayerOneshotRoute
  '/autoplayer/settings': typeof AutoplayerSettingsRoute
  '/api/autoplayer/ace-models': typeof ApiAutoplayerAceModelsRoute
  '/api/autoplayer/enhance-prompt': typeof ApiAutoplayerEnhancePromptRoute
  '/api/autoplayer/enhance-request': typeof ApiAutoplayerEnhanceRequestRoute
  '/api/autoplayer/enhance-session': typeof ApiAutoplayerEnhanceSessionRoute
  '/api/autoplayer/generate-cover': typeof ApiAutoplayerGenerateCoverRoute
  '/api/autoplayer/generate-song': typeof ApiAutoplayerGenerateSongRoute
  '/api/autoplayer/ollama-models': typeof ApiAutoplayerOllamaModelsRoute
  '/api/autoplayer/poll-ace': typeof ApiAutoplayerPollAceRoute
  '/api/autoplayer/refine-prompt': typeof ApiAutoplayerRefinePromptRoute
  '/api/autoplayer/save-song': typeof ApiAutoplayerSaveSongRoute
  '/api/autoplayer/submit-ace': typeof ApiAutoplayerSubmitAceRoute
  '/api/autoplayer/test-connection': typeof ApiAutoplayerTestConnectionRoute
  '/autoplayer/test/ace': typeof AutoplayerTestAceRoute
  '/autoplayer/test/connections': typeof AutoplayerTestConnectionsRoute
  '/autoplayer/test/cover': typeof AutoplayerTestCoverRoute
  '/autoplayer/test/e2e': typeof AutoplayerTestE2eRoute
  '/autoplayer/test/llm': typeof AutoplayerTestLlmRoute
  '/autoplayer/test': typeof AutoplayerTestIndexRoute
  '/api/autoplayer/audio/$songId': typeof ApiAutoplayerAudioSongIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autoplayer': typeof AutoplayerRoute
  '/mcp': typeof McpRoute
  '/autoplayer_/library': typeof AutoplayerLibraryRoute
  '/autoplayer_/oneshot': typeof AutoplayerOneshotRoute
  '/autoplayer_/settings': typeof AutoplayerSettingsRoute
  '/autoplayer_/test': typeof AutoplayerTestRouteWithChildren
  '/api/autoplayer/ace-models': typeof ApiAutoplayerAceModelsRoute
  '/api/autoplayer/enhance-prompt': typeof ApiAutoplayerEnhancePromptRoute
  '/api/autoplayer/enhance-request': typeof ApiAutoplayerEnhanceRequestRoute
  '/api/autoplayer/enhance-session': typeof ApiAutoplayerEnhanceSessionRoute
  '/api/autoplayer/generate-cover': typeof ApiAutoplayerGenerateCoverRoute
  '/api/autoplayer/generate-song': typeof ApiAutoplayerGenerateSongRoute
  '/api/autoplayer/ollama-models': typeof ApiAutoplayerOllamaModelsRoute
  '/api/autoplayer/poll-ace': typeof ApiAutoplayerPollAceRoute
  '/api/autoplayer/refine-prompt': typeof ApiAutoplayerRefinePromptRoute
  '/api/autoplayer/save-song': typeof ApiAutoplayerSaveSongRoute
  '/api/autoplayer/submit-ace': typeof ApiAutoplayerSubmitAceRoute
  '/api/autoplayer/test-connection': typeof ApiAutoplayerTestConnectionRoute
  '/autoplayer_/test/ace': typeof AutoplayerTestAceRoute
  '/autoplayer_/test/connections': typeof AutoplayerTestConnectionsRoute
  '/autoplayer_/test/cover': typeof AutoplayerTestCoverRoute
  '/autoplayer_/test/e2e': typeof AutoplayerTestE2eRoute
  '/autoplayer_/test/llm': typeof AutoplayerTestLlmRoute
  '/autoplayer_/test/': typeof AutoplayerTestIndexRoute
  '/api/autoplayer/audio/$songId': typeof ApiAutoplayerAudioSongIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/autoplayer'
    | '/mcp'
    | '/autoplayer/library'
    | '/autoplayer/oneshot'
    | '/autoplayer/settings'
    | '/autoplayer/test'
    | '/api/autoplayer/ace-models'
    | '/api/autoplayer/enhance-prompt'
    | '/api/autoplayer/enhance-request'
    | '/api/autoplayer/enhance-session'
    | '/api/autoplayer/generate-cover'
    | '/api/autoplayer/generate-song'
    | '/api/autoplayer/ollama-models'
    | '/api/autoplayer/poll-ace'
    | '/api/autoplayer/refine-prompt'
    | '/api/autoplayer/save-song'
    | '/api/autoplayer/submit-ace'
    | '/api/autoplayer/test-connection'
    | '/autoplayer/test/ace'
    | '/autoplayer/test/connections'
    | '/autoplayer/test/cover'
    | '/autoplayer/test/e2e'
    | '/autoplayer/test/llm'
    | '/autoplayer/test/'
    | '/api/autoplayer/audio/$songId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/autoplayer'
    | '/mcp'
    | '/autoplayer/library'
    | '/autoplayer/oneshot'
    | '/autoplayer/settings'
    | '/api/autoplayer/ace-models'
    | '/api/autoplayer/enhance-prompt'
    | '/api/autoplayer/enhance-request'
    | '/api/autoplayer/enhance-session'
    | '/api/autoplayer/generate-cover'
    | '/api/autoplayer/generate-song'
    | '/api/autoplayer/ollama-models'
    | '/api/autoplayer/poll-ace'
    | '/api/autoplayer/refine-prompt'
    | '/api/autoplayer/save-song'
    | '/api/autoplayer/submit-ace'
    | '/api/autoplayer/test-connection'
    | '/autoplayer/test/ace'
    | '/autoplayer/test/connections'
    | '/autoplayer/test/cover'
    | '/autoplayer/test/e2e'
    | '/autoplayer/test/llm'
    | '/autoplayer/test'
    | '/api/autoplayer/audio/$songId'
  id:
    | '__root__'
    | '/'
    | '/autoplayer'
    | '/mcp'
    | '/autoplayer_/library'
    | '/autoplayer_/oneshot'
    | '/autoplayer_/settings'
    | '/autoplayer_/test'
    | '/api/autoplayer/ace-models'
    | '/api/autoplayer/enhance-prompt'
    | '/api/autoplayer/enhance-request'
    | '/api/autoplayer/enhance-session'
    | '/api/autoplayer/generate-cover'
    | '/api/autoplayer/generate-song'
    | '/api/autoplayer/ollama-models'
    | '/api/autoplayer/poll-ace'
    | '/api/autoplayer/refine-prompt'
    | '/api/autoplayer/save-song'
    | '/api/autoplayer/submit-ace'
    | '/api/autoplayer/test-connection'
    | '/autoplayer_/test/ace'
    | '/autoplayer_/test/connections'
    | '/autoplayer_/test/cover'
    | '/autoplayer_/test/e2e'
    | '/autoplayer_/test/llm'
    | '/autoplayer_/test/'
    | '/api/autoplayer/audio/$songId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutoplayerRoute: typeof AutoplayerRoute
  McpRoute: typeof McpRoute
  AutoplayerLibraryRoute: typeof AutoplayerLibraryRoute
  AutoplayerOneshotRoute: typeof AutoplayerOneshotRoute
  AutoplayerSettingsRoute: typeof AutoplayerSettingsRoute
  AutoplayerTestRoute: typeof AutoplayerTestRouteWithChildren
  ApiAutoplayerAceModelsRoute: typeof ApiAutoplayerAceModelsRoute
  ApiAutoplayerEnhancePromptRoute: typeof ApiAutoplayerEnhancePromptRoute
  ApiAutoplayerEnhanceRequestRoute: typeof ApiAutoplayerEnhanceRequestRoute
  ApiAutoplayerEnhanceSessionRoute: typeof ApiAutoplayerEnhanceSessionRoute
  ApiAutoplayerGenerateCoverRoute: typeof ApiAutoplayerGenerateCoverRoute
  ApiAutoplayerGenerateSongRoute: typeof ApiAutoplayerGenerateSongRoute
  ApiAutoplayerOllamaModelsRoute: typeof ApiAutoplayerOllamaModelsRoute
  ApiAutoplayerPollAceRoute: typeof ApiAutoplayerPollAceRoute
  ApiAutoplayerRefinePromptRoute: typeof ApiAutoplayerRefinePromptRoute
  ApiAutoplayerSaveSongRoute: typeof ApiAutoplayerSaveSongRoute
  ApiAutoplayerSubmitAceRoute: typeof ApiAutoplayerSubmitAceRoute
  ApiAutoplayerTestConnectionRoute: typeof ApiAutoplayerTestConnectionRoute
  ApiAutoplayerAudioSongIdRoute: typeof ApiAutoplayerAudioSongIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoplayer': {
      id: '/autoplayer'
      path: '/autoplayer'
      fullPath: '/autoplayer'
      preLoaderRoute: typeof AutoplayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoplayer_/test': {
      id: '/autoplayer_/test'
      path: '/autoplayer/test'
      fullPath: '/autoplayer/test'
      preLoaderRoute: typeof AutoplayerTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoplayer_/settings': {
      id: '/autoplayer_/settings'
      path: '/autoplayer/settings'
      fullPath: '/autoplayer/settings'
      preLoaderRoute: typeof AutoplayerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoplayer_/oneshot': {
      id: '/autoplayer_/oneshot'
      path: '/autoplayer/oneshot'
      fullPath: '/autoplayer/oneshot'
      preLoaderRoute: typeof AutoplayerOneshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoplayer_/library': {
      id: '/autoplayer_/library'
      path: '/autoplayer/library'
      fullPath: '/autoplayer/library'
      preLoaderRoute: typeof AutoplayerLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoplayer_/test/': {
      id: '/autoplayer_/test/'
      path: '/'
      fullPath: '/autoplayer/test/'
      preLoaderRoute: typeof AutoplayerTestIndexRouteImport
      parentRoute: typeof AutoplayerTestRoute
    }
    '/autoplayer_/test/llm': {
      id: '/autoplayer_/test/llm'
      path: '/llm'
      fullPath: '/autoplayer/test/llm'
      preLoaderRoute: typeof AutoplayerTestLlmRouteImport
      parentRoute: typeof AutoplayerTestRoute
    }
    '/autoplayer_/test/e2e': {
      id: '/autoplayer_/test/e2e'
      path: '/e2e'
      fullPath: '/autoplayer/test/e2e'
      preLoaderRoute: typeof AutoplayerTestE2eRouteImport
      parentRoute: typeof AutoplayerTestRoute
    }
    '/autoplayer_/test/cover': {
      id: '/autoplayer_/test/cover'
      path: '/cover'
      fullPath: '/autoplayer/test/cover'
      preLoaderRoute: typeof AutoplayerTestCoverRouteImport
      parentRoute: typeof AutoplayerTestRoute
    }
    '/autoplayer_/test/connections': {
      id: '/autoplayer_/test/connections'
      path: '/connections'
      fullPath: '/autoplayer/test/connections'
      preLoaderRoute: typeof AutoplayerTestConnectionsRouteImport
      parentRoute: typeof AutoplayerTestRoute
    }
    '/autoplayer_/test/ace': {
      id: '/autoplayer_/test/ace'
      path: '/ace'
      fullPath: '/autoplayer/test/ace'
      preLoaderRoute: typeof AutoplayerTestAceRouteImport
      parentRoute: typeof AutoplayerTestRoute
    }
    '/api/autoplayer/test-connection': {
      id: '/api/autoplayer/test-connection'
      path: '/api/autoplayer/test-connection'
      fullPath: '/api/autoplayer/test-connection'
      preLoaderRoute: typeof ApiAutoplayerTestConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/submit-ace': {
      id: '/api/autoplayer/submit-ace'
      path: '/api/autoplayer/submit-ace'
      fullPath: '/api/autoplayer/submit-ace'
      preLoaderRoute: typeof ApiAutoplayerSubmitAceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/save-song': {
      id: '/api/autoplayer/save-song'
      path: '/api/autoplayer/save-song'
      fullPath: '/api/autoplayer/save-song'
      preLoaderRoute: typeof ApiAutoplayerSaveSongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/refine-prompt': {
      id: '/api/autoplayer/refine-prompt'
      path: '/api/autoplayer/refine-prompt'
      fullPath: '/api/autoplayer/refine-prompt'
      preLoaderRoute: typeof ApiAutoplayerRefinePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/poll-ace': {
      id: '/api/autoplayer/poll-ace'
      path: '/api/autoplayer/poll-ace'
      fullPath: '/api/autoplayer/poll-ace'
      preLoaderRoute: typeof ApiAutoplayerPollAceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/ollama-models': {
      id: '/api/autoplayer/ollama-models'
      path: '/api/autoplayer/ollama-models'
      fullPath: '/api/autoplayer/ollama-models'
      preLoaderRoute: typeof ApiAutoplayerOllamaModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/generate-song': {
      id: '/api/autoplayer/generate-song'
      path: '/api/autoplayer/generate-song'
      fullPath: '/api/autoplayer/generate-song'
      preLoaderRoute: typeof ApiAutoplayerGenerateSongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/generate-cover': {
      id: '/api/autoplayer/generate-cover'
      path: '/api/autoplayer/generate-cover'
      fullPath: '/api/autoplayer/generate-cover'
      preLoaderRoute: typeof ApiAutoplayerGenerateCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/enhance-session': {
      id: '/api/autoplayer/enhance-session'
      path: '/api/autoplayer/enhance-session'
      fullPath: '/api/autoplayer/enhance-session'
      preLoaderRoute: typeof ApiAutoplayerEnhanceSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/enhance-request': {
      id: '/api/autoplayer/enhance-request'
      path: '/api/autoplayer/enhance-request'
      fullPath: '/api/autoplayer/enhance-request'
      preLoaderRoute: typeof ApiAutoplayerEnhanceRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/enhance-prompt': {
      id: '/api/autoplayer/enhance-prompt'
      path: '/api/autoplayer/enhance-prompt'
      fullPath: '/api/autoplayer/enhance-prompt'
      preLoaderRoute: typeof ApiAutoplayerEnhancePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/ace-models': {
      id: '/api/autoplayer/ace-models'
      path: '/api/autoplayer/ace-models'
      fullPath: '/api/autoplayer/ace-models'
      preLoaderRoute: typeof ApiAutoplayerAceModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autoplayer/audio/$songId': {
      id: '/api/autoplayer/audio/$songId'
      path: '/api/autoplayer/audio/$songId'
      fullPath: '/api/autoplayer/audio/$songId'
      preLoaderRoute: typeof ApiAutoplayerAudioSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AutoplayerTestRouteChildren {
  AutoplayerTestAceRoute: typeof AutoplayerTestAceRoute
  AutoplayerTestConnectionsRoute: typeof AutoplayerTestConnectionsRoute
  AutoplayerTestCoverRoute: typeof AutoplayerTestCoverRoute
  AutoplayerTestE2eRoute: typeof AutoplayerTestE2eRoute
  AutoplayerTestLlmRoute: typeof AutoplayerTestLlmRoute
  AutoplayerTestIndexRoute: typeof AutoplayerTestIndexRoute
}

const AutoplayerTestRouteChildren: AutoplayerTestRouteChildren = {
  AutoplayerTestAceRoute: AutoplayerTestAceRoute,
  AutoplayerTestConnectionsRoute: AutoplayerTestConnectionsRoute,
  AutoplayerTestCoverRoute: AutoplayerTestCoverRoute,
  AutoplayerTestE2eRoute: AutoplayerTestE2eRoute,
  AutoplayerTestLlmRoute: AutoplayerTestLlmRoute,
  AutoplayerTestIndexRoute: AutoplayerTestIndexRoute,
}

const AutoplayerTestRouteWithChildren = AutoplayerTestRoute._addFileChildren(
  AutoplayerTestRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutoplayerRoute: AutoplayerRoute,
  McpRoute: McpRoute,
  AutoplayerLibraryRoute: AutoplayerLibraryRoute,
  AutoplayerOneshotRoute: AutoplayerOneshotRoute,
  AutoplayerSettingsRoute: AutoplayerSettingsRoute,
  AutoplayerTestRoute: AutoplayerTestRouteWithChildren,
  ApiAutoplayerAceModelsRoute: ApiAutoplayerAceModelsRoute,
  ApiAutoplayerEnhancePromptRoute: ApiAutoplayerEnhancePromptRoute,
  ApiAutoplayerEnhanceRequestRoute: ApiAutoplayerEnhanceRequestRoute,
  ApiAutoplayerEnhanceSessionRoute: ApiAutoplayerEnhanceSessionRoute,
  ApiAutoplayerGenerateCoverRoute: ApiAutoplayerGenerateCoverRoute,
  ApiAutoplayerGenerateSongRoute: ApiAutoplayerGenerateSongRoute,
  ApiAutoplayerOllamaModelsRoute: ApiAutoplayerOllamaModelsRoute,
  ApiAutoplayerPollAceRoute: ApiAutoplayerPollAceRoute,
  ApiAutoplayerRefinePromptRoute: ApiAutoplayerRefinePromptRoute,
  ApiAutoplayerSaveSongRoute: ApiAutoplayerSaveSongRoute,
  ApiAutoplayerSubmitAceRoute: ApiAutoplayerSubmitAceRoute,
  ApiAutoplayerTestConnectionRoute: ApiAutoplayerTestConnectionRoute,
  ApiAutoplayerAudioSongIdRoute: ApiAutoplayerAudioSongIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
